version: '3.8'
services:

  maven:
    build: maven-custom
      container_name: maven

  tomcat:
    build: tomcat-custom
    depends_on:
      - maven
    volumes:
      - maven:/home/test1/maven/boxfuse-sample-java-war-hello/
    ports:
      - "8080:8080"
      container_name: tomcat
