version: '3.8'
services:

  maven:
    build: maven-custom
    container_name: maven
    volumes:
      - maven_value:

  tomcat:
    build: tomcat-custom
    depends_on:
      - maven
    ports:
      - "8080:8080"
    container_name: tomcat
    volumes:
      - maven_value:

volumes:
    maven_value:/home/maven/boxfuse-sample-java-war-hello/

